Add Makefile for patient generation for EXM105
projecttacoma/fhir-patient-generator pull request #1
Opened 2020-01-13 17:27 UTC by mgramigna

[Companion Synthea PR](https://github.com/projecttacoma/synthea/pull/6)

Add Makefile for generating EXM105 patients. I decided to seed cqf-ruler with the full measure bundle now that the connectathon repo has them. 

*NOTE*: Change the synthea branch in the Makefile to `exm105` during testing until the Synthea PR is merged into `abacus`

2020-01-14 15:21 UTC, lukoktonos requested changes
Makefile working using the exm105 synthea branch. 1 minor suggestion to add a line to the README then looks good.

2020-01-14 15:21 UTC, lukoktonos commented on EXM105/Makefile
> +	calculate-bundles -d ./synthea/output/fhir_stu3 -c $(CQL_FILE) -u http://localhost:8080/cqf-ruler-dstu3/fhir
We should probably add instructions to do `npm install -g fhir-bundle-calculator` in the README of this repo

2020-01-14 17:08 UTC, mgramigna commented on EXM105/Makefile
> +	calculate-bundles -d ./synthea/output/fhir_stu3 -c $(CQL_FILE) -u http://localhost:8080/cqf-ruler-dstu3/fhir
Good call. Added details to README

2020-01-14 17:19 UTC, lukoktonos approved these changes

2020-01-17 18:56 UTC, okeefm approved these changes
Getting ~1/3 to ~1/2 Numerator patients, a handful of Denominator/IPOP patients, and the rest No Population patients, which sounds good to me.

2020-01-17 18:56 UTC, merged