Exm 105 R4
projecttacoma/fhir-patient-generator pull request #13
Opened 2020-03-06 15:29 UTC by okeefm

2020-03-06 21:52 UTC, mgramigna requested changes
Works as expected. Only change request is to use the same synthea cli flag motif as shown in #12 just so we don't have to update again once this gets merged?

2020-03-09 15:28 UTC, okeefm commented
Good call. Updated.

2020-03-09 18:18 UTC, mgramigna approved these changes

2020-03-09 19:56 UTC, tstrass approved these changes

2020-03-09 19:57 UTC, tstrass requested changes

2020-03-09 19:57 UTC, tstrass commented on EXM_105/Makefile
> +SYNTHEA_PROPS := ../synthea/src/main/resources/synthea.properties
This can be removed

2020-03-09 20:00 UTC, tstrass approved these changes

2020-03-09 20:02 UTC, mgramigna approved these changes

2020-03-10 13:01 UTC, merged