Update README to reflect current architecture
projecttacoma/fhir-patient-generator pull request #14
Opened 2020-03-09 22:08 UTC by mgramigna

[link to rendered version](https://github.com/projecttacoma/fhir-patient-generator/tree/update-readme/README.md)

2020-03-10 14:59 UTC, jbradl11 commented
Looks good. I recommend either mentioning that the user should confirm the `fhir-bundle-calculator` is up-to-date or include the `npm install` command in the make file (as we discussed).

2020-03-10 19:23 UTC, mgramigna commented
Pushed up instruction in the README for this. Also added #15 to add smarter checking of this to the code (not on the MITRE network right now, but will add a jira task as well once I am)

2020-03-12 12:57 UTC, tstrass requested changes

2020-03-12 12:57 UTC, tstrass commented on README.md
> +```
getting weird syntax highlighting on the `3>` since it's trying to interpret that as bash, maybe just omit `bash` in case that could be confusing.

2020-03-12 12:57 UTC, tstrass commented on README.md
> +make MEASURE_DIR=/path/to/measure/dir VERSION=x.y.z preload-<r4|stu3>
Ditto syntax highlighting comment.

2020-03-12 13:05 UTC, tstrass approved these changes

2020-03-12 13:05 UTC, merged