Added R4 Targets and fixtures for EXM125
projecttacoma/fhir-patient-generator pull request #5
Opened 2020-02-03 20:04 UTC by mgramigna

Synthea PR companion: https://github.com/projecttacoma/synthea/pull/9

**NOTE**: While reviewing, change line 77 of the `Makefile` to reference the `exm_125_r4` branch until the companion PR gets merged.

Testing: run `make r4` to generate R4 patients using the new module and calculate them against `cqf-ruler-r4`. Should see some mixed population results.

2020-02-04 23:18 UTC, hossenlopp requested changes

2020-02-04 23:18 UTC, hossenlopp commented on EXM_125/Makefile
> +	touch .setup-cqf-ruler
```suggestion
	touch .setup-cqf-ruler-r4
```

This should match the make target.

2020-02-05 13:08 UTC, mgramigna commented on EXM_125/Makefile
> +	touch .setup-cqf-ruler
Good catch. Should be resolved.

2020-02-05 13:40 UTC, hossenlopp approved these changes

2020-02-05 16:54 UTC, lukoktonos approved these changes

2020-02-05 17:25 UTC, hossenlopp approved these changes

2020-02-05 17:26 UTC, merged