EXM 104 R4 Support
projecttacoma/fhir-patient-generator pull request #7
Opened 2020-02-05 17:23 UTC by okeefm

Support for EXM 104 R4 in `fhir-patient-generator`

Also, migrated to using `connectathon`'s master branch, and using resources out of there instead of out of this repo, to mirror luke's PR.

### Testing instructions
* `make clean && make r4`
* Also probably worth testing `make clean && make` to test the STU3 patient generation

Before this can be merged

 After projecttacoma/synthea#10 is merged, update branch in Makefile

2020-02-05 17:51 UTC, mgramigna requested changes
Looks good. One suggestion that I have is to not include the `fhir` and `fhir_stu3` directories in the `patients-r4` and `patients-stu3` directories respectively. I think it's fine if the directory structure appears as follows

![image](https://user-images.githubusercontent.com/16297930/73868270-28d8d200-4816-11ea-9287-b58e914e071b.png) (with IPOP if it has people too)

2020-02-05 20:03 UTC, mgramigna approved these changes

2020-02-06 14:54 UTC, lukoktonos requested changes
- [x] stu3 working with vs
- [x] stu3 working with no-vs (Library id needs to be `measure-EXM104-FHIR3-8.1.000` for PUT request)
- [x] r4 working with vs (~still getting calculation error mentioned in synthea pr both with cqf-ruler in docker and running locally on `develop` branch~ fixed with `mvn clean`).
- [x] r4 working with no-vs (paths need to be updated, added suggestions in-line)

2020-02-06 14:54 UTC, losborne commented on EXM_104/Makefile
>  	$(info connectathon checks out a specific commit SHA in case filepaths are updated)
```suggestion
```

2020-02-06 14:54 UTC, losborne commented on EXM_104/Makefile
> +	git clone --single-branch --branch exm_104_r4 --depth 1 https://github.com/projecttacoma/synthea.git
```suggestion
	git clone --single-branch --branch abacus --depth 1 https://github.com/projecttacoma/synthea.git
```

Will need to be updated once https://github.com/projecttacoma/synthea/pull/10 gets in

2020-02-06 14:54 UTC, losborne commented on EXM_104/Makefile
> +	-d @connectathon/fhir4/resources/measure/measure-EX104_FHIR4-8.1.000.json
```suggestion
	-d @connectathon/fhir4/bundles/EXM104_FHIR4-8.1.000/EXM104_FHIR4-8.1.000-files/measure-EXM104_FHIR4-8.1.000.json
```

2020-02-06 14:54 UTC, losborne commented on EXM_104/Makefile
> +	-d @connectathon/fhir4/resources/library/all-libraries-bundle.json
```suggestion
	-d @connectathon/fhir4/bundles/EXM105_FHIR4-8.1.000/EXM105_FHIR4-8.1.000-files/library-deps-EXM105_FHIR4-8.1.000-bundle.json
```

2020-02-07 13:51 UTC, okeefm commented
Fixed the seed issues/other suggested issuses. Should be ready for re-review.

2020-02-07 14:08 UTC, lukoktonos requested changes

2020-02-07 14:08 UTC, losborne commented on EXM_104/Makefile
> +	curl -X POST \
```suggestion
	curl -X PUT \
```

2020-02-07 14:08 UTC, losborne commented on EXM_104/Makefile
> +  http://localhost:8080/cqf-ruler-r4/fhir/ \
```suggestion
  http://localhost:8080/cqf-ruler-r4/fhir/Library/library-EXM104-FHIR4-8.1.000 \
```

2020-02-07 14:52 UTC, lukoktonos approved these changes

2020-02-07 15:03 UTC, merged