CMS124 R4 Patient Generation.
projecttacoma/fhir-patient-generator pull request #8
Opened 2020-02-06 16:15 UTC by hossenlopp

- Replaces STU3 data with fresh data with a measure report.
- Removes `.cql` file used to STU3 and replaces it with using bundles from Connectathon repo.
- Adds R4 generation.
- Adds R4 patients.

For testing R4 generation, modify line 71 of `Makefile` to use `exm_124_r4` branch of Synthea if https://github.com/projecttacoma/synthea/pull/11 is not merged yet.

2020-02-06 17:45 UTC, lukoktonos requested changes
- [x] stu3 works
- [x] stu3 no-vs works 
- [x] r4 works
- [x] r4 no-vs works (~_ to -, suggested fix~ fixed)

Just 1 small fix then looks good

2020-02-06 17:45 UTC, losborne commented on EXM_124/Makefile
> +  http://localhost:8080/cqf-ruler-r4/fhir/Measure/measure-EXM124_FHIR4-8.2.000 \
```suggestion
  http://localhost:8080/cqf-ruler-r4/fhir/Measure/measure-EXM124-FHIR4-8.2.000 \
```

2020-02-06 18:02 UTC, lukoktonos approved these changes
Looks good!

2020-02-11 00:20 UTC, mgramigna approved these changes
Looks good

2020-02-11 00:21 UTC, merged